export const FETCH_LOCATION = "FETCH_LOCATION"
export const FETCH_CATEGORY_BY_BRANCH = "FETCH_CATEGORY_BY_BRANCH"
export const FETCH_CATEGORY_BY_LOCATION = "FETCH_CATEGORY_BY_LOCATION"
export const FETCH_SUBCATEGORY = "FETCH_SUBCATEGORY"